### ISSUE TITLE
`ffmpeg-mpp` & `ffmpeg4.4-mpp`: Document-related building failure

### ISSUE THREAD

**Issue by 7Ji** [7Ji-PKGBUILDs/.meta#1]
```
Nov 20 19:57:52 o5p python[2919182]: MAN        doc/ffplay.1
Nov 20 19:57:52 o5p python[2919182]: /bin/sh: line 1: pod2man: command not found
Nov 20 19:57:52 o5p python[2919182]: make: *** [doc/Makefile:97: doc/ffplay.1] Error 127
Nov 20 19:57:52 o5p python[2919182]: make: *** Waiting for unfinished jobs....
Nov 20 19:57:52 o5p python[2919182]: ==> ERROR: A failure occurred in build().
Nov 20 19:57:52 o5p python[2919182]:     Aborting...
Nov 20 19:57:52 o5p python[2919182]: [2023-11-20T11:57:52Z INFO  arch_repo_builder::build::builder] End of log for building 'ffmpeg-mpp'
Nov 20 19:57:52 o5p python[2919182]: [2023-11-20T11:57:52Z ERROR arch_repo_builder::build::builder] Failed to build 'ffmpeg-mpp'
```
Some dependency upgrade triggered a rebuild of `ffmpeg-mpp` and it failed to build with the latest dependencies, I didn't look into which yet, but maybe adding `pod2man` to dep could fix this?

**Comment by kyak** [comment]
Yes, it always required `pod2man` which was missing from dependencies.

I pointed to this problem once, but it got lost in AUR discussion :)

**Comment by hbiyik** [comment]
ugh kill me, i will update when i am back to home

**Comment by 7Ji** [comment]
No need to hurry. The last successful build still sits there safely. Using the old build won't necessarily break. It's just that I design the builder to rebuild on any dependency change, so I don't need to manually trigger rebuild if some package does break with newer dependency.

**Comment by 7Ji** [comment]
@hbiyik 
Sorry but the packages were built successfully just now with newer dephashes, so the previous build errors seem be caused by some upstream alarm update that was only partially synced to their mirrors.

Closing now.

**Comment by 7Ji** [comment]
Turns out this was caused by systemd's hardcoded `PATH`:

https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#Environment%20Variables%20Set%20or%20Propagated%20by%20the%20Service%20Manager

**Comment by 7Ji** [comment]
The builder was fixed in https://github.com/7Ji/arch_repo_builder/commit/89c22e940e4af88aa84f4403caab9258e5fc8c1a , we should no longer have weird missing binary issues.
