### ISSUE TITLE
libvpx (1.14.0-1) breaks dependency 'libvpx.so=8-64' required by ffmpeg-mpp

### ISSUE THREAD

**Issue by kyak** [7Ji-PKGBUILDs/.meta#18]
There is an error during upgrade:

```
error: failed to prepare transaction (could not satisfy dependencies)
:: installing libvpx (1.14.0-1) breaks dependency 'libvpx.so=8-64' required by ffmpeg-mpp
```

**Comment by 7Ji** [comment]
Not a PKGBUILD issue but a repo package issue. 

The change in dependency already triggered a rebuild an hour ago, you'll need to remove your locally cached ffmpeg-mpp from /var/cache/pacman/pkg and pacman -Syu to install again.

https://github.com/7Ji/archrepo?tab=readme-ov-file#aggresive-rebuild-warning

I'm rewriting the builder to add an additional suffix to mark rebuild count, if I could finished that then you would not have such problems any more. For now, please use the above workaround.
