### ISSUE TITLE
`ffmpeg-mpp`: To build the package from development branch

### ISSUE THREAD

**Issue by kyak** [7Ji-PKGBUILDs/.meta#2]
Currently this package is shipping a hand-crafted patch.

I think it would be better to designate a development branch in https://github.com/hbiyik/ffmpeg/ and build from there.

I'm currently using this branch: https://github.com/hbiyik/ffmpeg/tree/exp_refactor_all

For now I have to build ffmpeg manually from this branch and then point kodi there, which is not very good.

pinging @hbiyik

**Comment by hbiyik** [comment]
no, this branch is still experimental, and encoder part is completely broken, when i have confidence that it works fine, i will make this as master branch and update the patches. But it is too early at this point.

**Comment by kyak** [comment]
Thanks, I'm closing this for now then.
