### ISSUE TITLE
Building kodi-nexus-mpp-git fails

### ISSUE THREAD

**Issue by erayrafet** [7Ji-PKGBUILDs/.meta#20]
![Screenshot from 2024-02-18 19-47-48](https://github.com/7Ji-PKGBUILDs/.report/assets/34194191/f9a00f90-7a30-42fa-a16f-b408c24a148c)
Running this on Arch on the Khadas Edge 2.

**Comment by 7Ji** [comment]
That's a network problem, not a PKGBUILD problem, please check your connection.

**Comment by erayrafet** [comment]
It appears that the package hasn't been built by boogie for Arch either.

**Comment by hbiyik** [comment]
@erayrafet i will switch to a new transport mechanism soon which will 2x or 3x improve the download time and storage requirements. Still need more time though.

Sneak peek:
https://github.com/hbiyik/agrrepo/tree/next/gitweb-dlagent

When finished, we can rectify both 7jipkgbuilds and agrrepo and reuse the same packages at once.

**Comment by hbiyik** [comment]
@dont worry i will update, you can use the stuff here if you have urgency https://github.com/hbiyik/agrrepo/tree/master/kodi/20-nexus.

currently there is shit loads of discussion on how to manage the package names an etc, so a lot going on..

**Comment by erayrafet** [comment]
> @dont worry i will update, you can use the stuff here if you have urgency https://github.com/hbiyik/agrrepo/tree/master/kodi/20-nexus.
> 
> currently there is shit loads of discussion on how to manage the package names an etc, so a lot going on..

Well, the build I got installed yesterday. Currently Samuel (kwankiu) and I are testing the 6.1 kernel and Kodi reports that it's using software decoding while Chromium is supposedly using hw decoding.
Do you have any tips for verifying that? This is more of an mpp issue, perhaps. Dunno honestly but since we started...
![image (1)](https://github.com/7Ji-PKGBUILDs/.meta/assets/34194191/4b961f4a-d8dc-4721-9d28-bbdfe0115e1a)
![image](https://github.com/7Ji-PKGBUILDs/.meta/assets/34194191/80df8bce-0d31-48bf-8903-81b3e41bebd0)

**Comment by hbiyik** [comment]
did you this docu?

https://github.com/hbiyik/ffmpeg-rockchip/wiki/Rendering#kodi

**Comment by erayrafet** [comment]
Nope. Something for me to test. I'll report back.

**Comment by erayrafet** [comment]
> did you this docu?
> 
> https://github.com/hbiyik/ffmpeg-rockchip/wiki/Rendering#kodi

![image](https://github.com/7Ji-PKGBUILDs/.meta/assets/34194191/04a7b575-afcc-445b-bf80-ed56a86620c6)
![image](https://github.com/7Ji-PKGBUILDs/.meta/assets/34194191/4887fa2c-286c-4e72-addc-a064cbe6c745)
Glitchy and no EGL option.

That's with kernel 6.1 from Joshua, Panfork, Wayland, Gnome, mpp-git.

**Comment by hbiyik** [comment]
is this gbm?

if there is no EGL option there might be something wrong in your panfork.

There is this patch about panfork but it shouldn't prevent EGL disappaering.
https://github.com/7Ji-PKGBUILDs/mesa-panfork-git/blob/master/001-disable_native_fences.patch

I just tested with joshua's 6.1 + panfork on gbm it works fine on my end, i am on arch btw :)

EDIT:
(ah sorry you mentioned wayland allready)

I did not test wayland yet, i will look at it

**Comment by erayrafet** [comment]
> is this gbm?
> 
> if there is no EGL option there might be something wrong in your panfork.
> 
> There is this patch about panfork but it shouldn't prevent EGL disappaering. https://github.com/7Ji-PKGBUILDs/mesa-panfork-git/blob/master/001-disable_native_fences.patch
> 
> I just tested with joshua's 6.1 + panfork on gbm it works fine on my end, i am on arch btw :)
> 
> EDIT: (ah sorry you mentioned wayland allready)
> 
> I did not test wayland yet, i will look at it

![image](https://github.com/7Ji-PKGBUILDs/.meta/assets/34194191/4ddc898a-6e86-423c-a4c3-a8f9f04736a2)

EGL is here. I'm on Arch by Kwankiu.
