### ISSUE TITLE
about linux-rockchip-joshua-bin

### ISSUE THREAD

**Issue by wyf9661** [7Ji-PKGBUILDs/.meta#21]
I create a `-bin` [repo](https://github.com/7Ji-PKGBUILDs/linux-rockchip-joshua-bin) package kernel pkg with joshua's pre built kernel module and headers. 
the `7ji repo` may not set up building recently, If you do not want to build kernel, just use these repo.@JFLim1 @kwankiu
Also you can change the url to kernel 6.1 with kernel joshua already built.

**Comment by wyf9661** [comment]
The kernel deb package of the latest v6.1 are as belows.
https://github.com/Joshua-Riek/ubuntu-rockchip/actions/runs/7978727659
![image](https://github.com/7Ji-PKGBUILDs/.report/assets/122584107/885a6c89-f5d7-493c-8967-8026e8b6cbd4)

**Comment by wyf9661** [comment]
@7Ji FYI

**Comment by JFLim1** [comment]
> I create a `-bin` [repo](https://github.com/7Ji-PKGBUILDs/linux-rockchip-joshua-bin) package kernel pkg with joshua's pre built kernel module and headers.
> the `7ji repo` may not set up building recently, If you do not want to build kernel, just use these repo

Do you mean in future 7Ji Repo will have linux-rockchip-joshua-bin-6.1?  Not familiar in building kernels.

**Comment by wyf9661** [comment]
> Do you mean in future 7Ji Repo will have linux-rockchip-joshua-bin-6.1? Not familiar in building kernels.

there's no necessary connection between `7Ji repo` and `7ji-PKGBUILDs`

**Comment by JFLim1** [comment]
> 7ji-PKGBUILDs

How do I install linux-rockchip-joshua-bin - kernel 6.1 from 7Ji-PKGBUILDs?  Exact commands.  Am really new to this.

**Comment by wyf9661** [comment]
> How do I install linux-rockchip-joshua-bin - kernel 6.1 from 7Ji-PKGBUILDs? Exact commands. Am really new to this.

Download the repo and using `makepkg`.You can look it up in arch wiki, as it is not a repo issue.
Mainwhile, I have already pushed it to [aur](https://aur.archlinux.org/packages/linux-rockchip-joshua-bin), you can simply install it by `paru -S linux-rockchip-joshua-bin`
and change the PKGBUILD as well.
```
jat@opi5plus:~> paru -S linux-rockchip-joshua-bin
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) linux-rockchip-joshua-bin-5.10.160.31-1

:: Proceed to review? [Y/n]:

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
:: Accept changes? [Y/n]:
```

**Comment by JFLim1** [comment]
> linux-rockchip-joshua-bin-5.10.160.31-1

This version is already available from 7Ji-Repo which I am using on KDE-Wayland.  

Wanted to test Joshua Riek latest 6.1.43 on Arch Linux.  Is thee a "bin" package for Joshua-kernel-6.1?  What command for this?  

paru -S linux-rockchip-joshua-6.1.43-bin?

or is it

paru -S https://github.com/Joshua-Riek/ubuntu-rockchip/actions/runs/7978727659

[jfl@opi5plus ~]$ paru -S https://github.com/Joshua-Riek/ubuntu-rockchip/actions/runs/7978727659
bash: paru: command not found

[jfl@opi5plus ~]$ yay -S https://github.com/Joshua-Riek/ubuntu-rockchip/actions/runs/7978727659
 -> database https: not found

Edit:
Presume will have to install "paru-bin" from AUR first.  Still need to know the command to install the joshua's kernel-6.1.

**Comment by wyf9661** [comment]
I won't change pkgbuild unless thre be a release of 6.1 from joshua, as all the beta version may have risk of crash or any other problem which causes the bad performance of board.
If you want to have a try, you must exactly know what you are doing and have the ability of recover your environment.If you really new to this, you 'd better stick to which kernel version upstream keeps.

**Comment by kwankiu** [comment]
> Is thee a "bin" package for Joshua-kernel-6.1? What command for this?
I just modified the PKGBUILD for 6.1 here

https://github.com/kwankiu/linux-rkbsp-joshua-bin

**Comment by kwankiu** [comment]
@wyf9661 I just extracted the 6.1 package and it seems only contains one file (vmlinuz-6.1.43-1-rockchip) which doesnt seems to be enough to build the kernel package.

Updates: 
https://github.com/Joshua-Riek/ubuntu-rockchip/actions/runs/7999186089 has a full package
https://launchpad.net/~jjriek/+archive/ubuntu/kernel/ seems broken or not updated

**Comment by kwankiu** [comment]
Answer from Joshua:

![IMG_0247](https://github.com/7Ji-PKGBUILDs/.report/assets/29329276/7f505d16-7f32-4fc9-8398-764e47354934)

**Comment by wyf9661** [comment]
> Updates: https://github.com/Joshua-Riek/ubuntu-rockchip/actions/runs/7999186089 has a full package

I know this situation, so I mentioned
> The kernel deb package of the latest v6.1 are as belows. https://github.com/Joshua-Riek/ubuntu-rockchip/actions/runs/7978727659 ![image](https://private-user-images.githubusercontent.com/122584107/306616728-885a6c89-f5d7-493c-8967-8026e8b6cbd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTY0MDgsIm5iZiI6MTcwODY1NjEwOCwicGF0aCI6Ii8xMjI1ODQxMDcvMzA2NjE2NzI4LTg4NWE2Yzg5LWY1ZDctNDkzYy04OTY3LTgwMjZlOGI2Y2JkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QwMjQxNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lN2VmNmM0NWEyZGNhNzA5MzhmYWU1NGJmMWYwNTczMzUxMzcwZjEyODA2ZTdmMWI5MGVmMzYxYTE3NTAwZWNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4NnP_LprfgI8apyf99UPxxjG_yn46k6eXq85peUfH0c)

If you want to bump to kernel 6.1, you need to download this zip and `unzip` it to your build dir and change `PKGBUILD` of source from `url` to `local file` like this
```
source=(
  "linux-image-${_pkgver}-rockchip_${_pkgver}-${_buildver}_arm64.deb"
  "linux-headers-${_pkgver}-rockchip_${_pkgver}-${_buildver}_arm64.deb"
  "linux.preset"
)
```
```
jat@opi5plus:linux-rockchip-joshua-bin> ls -l
总计 126580
-rw-r--r-- 1 jat jat    35149  2月21日 19:18 LICENSE
-rw-r--r-- 1 jat jat  8845106  2月22日 04:37 linux-headers-6.1.43-rockchip_6.1.43-1_arm64.deb
-rw-r--r-- 1 jat jat 32761044  2月22日 04:37 linux-image-6.1.43-rockchip_6.1.43-1_arm64.deb
-rw-r--r-- 1 jat jat      232  2月21日 19:19 linux.preset
-rw-r--r-- 1 jat jat 36525340  2月22日 13:40 linux-rockchip-joshua-bin-6.1.43.1-1-aarch64.pkg.tar.xz
-rw-r--r-- 1 jat jat  9864516  2月22日 13:41 linux-rockchip-joshua-bin-headers-6.1.43.1-1-aarch64.pkg.tar.xz
-rw-r--r-- 1 jat jat 41562950  2月22日 13:36 linux-rockchip.zip
drwxr-xr-x 1 jat jat      116  2月22日 13:40 pkg
-rw-r--r-- 1 jat jat     3259  2月21日 20:39 PKGBUILD
drwxr-xr-x 1 jat jat      318  2月22日 11:56 src
jat@opi5plus:linux-rockchip-joshua-bin>
```
To be honest, you dont't need to hurry as the stable kernel will be published soon.That's why I said
> I won't change pkgbuild unless thre be a release of 6.1 from joshua, as all the beta version may have risk of crash or any other problem which causes the bad performance of board.

**Comment by kwankiu** [comment]
added a new PKGBUILD for 6.1

https://github.com/kwankiu/acu/tree/pkgbuilds/linux-rockchip-6-joshua-bin

**Comment by wyf9661** [comment]
@JFLim1 @kwankiu I create a nightly release [repo](https://github.com/wyf9661/ubuntu-rockchip/releases) to build joshua's kernel with `HEAD` of git automatically.
![image](https://github.com/7Ji-PKGBUILDs/.report/assets/122584107/785d9bfd-3c97-450b-bc8e-dae98330b50f) 
Also update the [joshua-bin](https://github.com/7Ji-PKGBUILDs/linux-rockchip-joshua-bin) pkg with daily build. 
![image](https://github.com/7Ji-PKGBUILDs/.report/assets/122584107/aa6a9354-bb24-4438-afd9-d3440296d88f)
You can install this if you'd like to have try, but notice it will not be so stable as joshua may update the upstream repo at all time.
