### ISSUE TITLE
chromium-mpp is broken with current Arch Linux ARM's libjxl 0.10

### ISSUE THREAD

**Issue by kwankiu** [7Ji-PKGBUILDs/.meta#22]
chromium-mpp is broken with current Arch Linux ARM's libjxl 0.10

chromium needs to be rebuilt or needs to be linked to generic libjxl

**Comment by 7Ji** [comment]
Sorry, the suspension on one of my VPSs which I used to sync my local repo to Github releases was lifted, and as I've switched the job to another server, they were fighting to sync their local files. The result is some packages being "downgraded" by the "resurrectted" server. I've turned it off and restarted the syncing, things should come back to normal soon.

**Comment by 7Ji** [comment]
This should have been fixed.
