### ISSUE TITLE
Feedback: MPV FFMPEG-ROCKCHIP-GIT MPP-GIT  10Bit-HEVC Video Blue Screen No Video Output

### ISSUE THREAD

**Issue by JFLim1** [7Ji-PKGBUILDs/.meta#23]
Device: Opi5-Plus

Using kernel 5.10.160

mpv will only output Blank Blue Screen with 10Bit hevc video eventhough "mpv.conf" has "vf-add=scale_rkrga=force_yuv=auto" enabled.

```
mpv /home/jfl/Videos/jellyfish-120-mbps-4k-uhd-hevc-10bit.mkv
 (+) Video --vid=1 (*) (hevc 3840x2160 29.970fps)
Using hardware decoding (rkmpp).
rga_api version 1.9.3_[2]
VO: [gpu-next] 3840x2160 drm_prime[p010]
[vo/gpu-next/drmprime] unsupported DRM image format p010
[vo/gpu-next] Initializing texture for hardware decoding failed.
[vo/gpu-next/libplacebo] Failed mapping frame id 0 with PTS 0.000000
[vo/gpu-next] Failed updating frames!
[vo/gpu-next/drmprime] unsupported DRM image format p010
[vo/gpu-next] Initializing texture for hardware decoding failed.
[vo/gpu-next/libplacebo] Failed mapping frame id 1 with PTS 0.016667
[vo/gpu-next] Failed updating frames!
[vo/gpu-next/drmprime] unsupported DRM image format p010
[vo/gpu-next] Initializing texture for hardware decoding failed.
[vo/gpu-next/libplacebo] Failed mapping frame id 3 with PTS 0.050000
[vo/gpu-next] Failed updating frames!

8Bit hevc video play without issue with vpu hw acceleration
mpv /home/jfl/Videos/jellyfish-120-mbps-4k-uhd-h264.mkv
 (+) Video --vid=1 (*) (h264 3840x2160 29.970fps)
Using hardware decoding (rkmpp).
rga_api version 1.9.3_[2]
VO: [gpu-next] 3840x2160 drm_prime[nv12]
Exiting... (Quit)

```
When on kernel-6.1.43, mpv has NO vpu hw acceleration with any video.

The "mpv.conf" settings:

```
hwdec=rkmpp

# Specify default video output.
#vo=gpu
vo=gpu-next

# Use X11 backend, its much faster than wayland
#gpu-context=x11egl

# This is required, removing will increase droped frames
vf-add=fps=60:round=near
```

**Comment by nyanmisaka** [comment]
https://github.com/hbiyik/ffmpeg-rockchip/wiki/Rendering#required-patches-and-fixes-in-the-toolchain

> VO: [gpu-next] 3840x2160 drm_prime[p010]
> [vo/gpu-next/drmprime] unsupported DRM image format p010

You have to use `mpv-git`, otherwise the newly added `nv16/p010/p210` formats are not supported.

**Comment by JFLim1** [comment]
> You have to use `mpv-git`, otherwise the newly added `nv16/p010/p210` formats are not supported.

Hi @nyanmisaka,

Thanks.  Is there a prebuilt mpv-git-bin available? 

Is vpu hw acceleration supported with kernel-6.1.43-joshua?

**Comment by 7Ji** [comment]
There will never be a pre-built -bin package. It's against the idea of a repo and me building it does not really help any one using the repo. If there is -bin PKGBUILD, build by yourself.

**Comment by JFLim1** [comment]
> You have to use `mpv-git`, otherwise the newly added `nv16/p010/p210` formats are not supported.

Will this AUR [mpv-git](https://aur.archlinux.org/packages/mpv-git)	0.37.0_114_g17be6e1990-1 surfice or works? 

yay -S mpv-git

**Comment by JFLim1** [comment]
> https://github.com/hbiyik/ffmpeg-rockchip/wiki/Rendering#required-patches-and-fixes-in-the-toolchain
> 
> > VO: [gpu-next] 3840x2160 drm_prime[p010]
> > [vo/gpu-next/drmprime] unsupported DRM image format p010
> 
> You have to use `mpv-git`, otherwise the newly added `nv16/p010/p210` formats are not supported.

Hi @nyanmisaka & @7Ji,

Thank you for the great support and work.

With mpv-git 0.37.0_476_g9ac791c329-1 (actually had compile this a while ago but forgotten about it) 4K-10bit HEVC videos played/streamed well -- this is with linux-rockchip-joshua 5.10.160.31-2 kernel.

```
10bit HEVC
[jfl@opi5plus ~]$ mpv /home/jfl/Videos/jellyfish-120-mbps-4k-uhd-hevc-10bit.mkv
 (+) Video --vid=1 (*) (hevc 3840x2160 29.970fps)
Using hardware decoding (rkmpp).
rga_api version 1.9.3_[2]
VO: [gpu-next] 3840x2160 drm_prime[p010]
V: 00:00:29 / 00:00:30 (100%)
Exiting... (End of file)

10bit HEVC
[jfl@opi5plus ~]$ mpv https://www.youtube.com/watch?v=k7dy1B6bOeM
 (+) Video --vid=1 (*) (vp9 3840x2160 59.940fps)
 (+) Audio --aid=1 --alang=eng (*) (eac3 6ch 48000Hz)
File tags:
 Uploader: 4K Video ULTRA HD
 Channel_URL: https://www.youtube.com/channel/UCRauo6y9tx0FB0OLLtqLA-g
Using hardware decoding (rkmpp).
rga_api version 1.9.3_[2]
AO: [pipewire] 48000Hz 5.1(side) 6ch floatp
VO: [gpu-next] 3840x2160 drm_prime[p010]
AV: 00:11:11 / 00:11:11 (100%) A-V:  0.000 Dropped: 3 Cache: 0.0s
Exiting... (End of file)
[jfl@opi5plus ~]$
```

But unfornately with linux-rkbsp-joshua-git 6.1.43.r1266027.91f86fce9b8b-1 there is NO vpu hw acceleration support.   Will there vpu hw acceleration support on bsp kernel 6.1?

```
[jfl@opi5plus ~]$ mpv https://www.youtube.com/watch?v=k7dy1B6bOeM
 (+) Video --vid=1 (*) (vp9 3840x2160 59.940fps)
 (+) Audio --aid=1 --alang=eng (*) (eac3 6ch 48000Hz)
File tags:
 Uploader: 4K Video ULTRA HD
 Channel_URL: https://www.youtube.com/channel/UCRauo6y9tx0FB0OLLtqLA-g
[ffmpeg/video] vp9_rkmpp: Failed to init MPP context: -1
Could not open codec.
[ffmpeg] Impossible to convert between the formats supported by the filter 'mpv_src_default_in' and the filter 'auto_scale_0'
[lavfi] failed to configure the filter graph
Disabling filter scale_rkrga.00 because it has failed.
[ffmpeg] Impossible to convert between the formats supported by the filter 'mpv_src_default_in' and the filter 'auto_scale_0'
[lavfi] failed to configure the filter graph
Disabling filter scale_rkrga.01 because it has failed.
AO: [pipewire] 48000Hz 5.1(side) 6ch floatp
VO: [gpu-next] 3840x2160 yuv420p10

Audio/Video desynchronisation detected! Possible reasons include too slow
hardware, temporary CPU spikes, broken drivers, and broken files. Audio
position will not match to the video (see A-V status field).
Consider trying `--profile=fast` and/or `--hwdec=auto-safe` as they may help.

AV: 00:00:11 / 00:11:11 (2%) A-V:  0.924 Dropped: 559 Cache: 13s/51MB
Exiting... (Quit)
[jfl@opi5plus ~]$
```

**Comment by hbiyik** [comment]
@JFLim1 
https://github.com/7Ji-PKGBUILDs/mpp-git/commit/e35dcd935be1f25a86d580394c2a071994a4aadf

Or

https://github.com/7Ji-PKGBUILDs/mpp/commit/d2afd126b90b8f946d7e9fe2851495f74f6781b0

should fix the problem.

Edit: oops i noticed i forgot to update .SRCINFO in mpp-git pkg, ill do it later. Mpp pkg should work fine after rebuilt.

**Comment by JFLim1** [comment]
Hi @7Ji & @hbiyik,

With Install mpp-git 1.0.4.r3472.fdeb8c37-3 and linux-rkbsp-joshua-git 6.1.43.r1266030.d3e66fee7db6-1 or linux-rockchip-joshua-bin 6.1.43.20240305-1, mpv-git runs with vpu hw acceleration. 

Thank you.

```
mpv /home/jfl/Videos/jellyfish-120-mbps-4k-uhd-hevc-10bit.mkv 
 (+) Video --vid=1 (*) (hevc 3840x2160 29.970fps)
Using hardware decoding (rkmpp).
rga_api version 1.10.0_[8]
VO: [gpu-next] 3840x2160 drm_prime[p010]
V: 00:00:29 / 00:00:30 (100%) Dropped: 1
Exiting... (End of file)
```
