### ISSUE TITLE
Kernel rename announcement

### ISSUE THREAD

**Issue by 7Ji** [7Ji-PKGBUILDs/.meta#24]
As we're maintaining more and more kernel packages, we need to make clear which kernel package is for which platform. 

Therefore, we're going to rename all kernel packages to follow the naming style documented in [Kernel package guidelines](https://github.com/7Ji-PKGBUILDs/.meta/blob/main/PackageGuidelines.md#kernel-package-guidelines). 

This would bring a painful transition as any one who has installed these kernel packages would need to manually edit their booting configurations, but it would improve the long-time maintainability greatly.

I've already renamed the following kernel packages:
 - [linux-aarch64-rockchip-rk3588-bsp5.10-orangepi-git](https://github.com/7Ji-PKGBUILDs/linux-aarch64-rockchip-rk3588-bsp5.10-orangepi-git): from `linux-aarch64-orangpi5-git`
 - [linux-aarch64-rockchip-rk3588-bsp5.10-orangepi](https://github.com/7Ji-PKGBUILDs/linux-aarch64-rockchip-rk3588-bsp5.10-orangepi): from `linux-aarch64-orangpi5`

@wyf9661 has renamed the following packages:
- [linux-aarch64-rockchip-rk5.10-joshua](https://github.com/7Ji-PKGBUILDs/linux-aarch64-rockchip-rk5.10-joshua): from `linux-rockchip-joshua`
- [linux-aarch64-rockchip-rk6.1-joshua-git](https://github.com/7Ji-PKGBUILDs/linux-aarch64-rockchip-rk6.1-joshua-git): from `linux-rockchip-joshua-git`

Renaming of other kernel packages should be tracked on this issue.

@hbiyik FYI

**Comment by hbiyik** [comment]
@7Ji thanks i will work on it most likely on weekend.

one question, rockchip bsp is not meant to work on aarch64 only, it also works on armv7? isnt it misleading? espcially radxa maintained bsp has several of armv7 devices supported, should be similar for joshuas.

**Comment by 7Ji** [comment]
The source should work, but the PKGBUILD only builds for aarch64 currently.

If the PKGBUILD is multi-arch and can build for multiple arch natively, then the arch could be omitted.

But I think implementing that in a single PKGBUILD would be tricky. Keeping it aarch64-only on another hand is easier.

**Comment by hbiyik** [comment]
ok lets keep it aarch64, if someone else really uses it armv7 then it would that day's problem, currently there is nobobdy.

**Comment by hbiyik** [comment]
@wyf9661 @7Ji 
dont want to be a nit picker but the is it helpfull to harmonize the bsp suffix?

linux-aarch64-rockchip-rk3588-**bsp5.10**-orangepi-git
linux-aarch64-rockchip-**rk5.10**-joshua

i think rockchip is already mentioned in name, so would it make more sense to use bsp instead of rk prefix like below?

linux-aarch64-rockchip-**bsp5.10**-joshua
linux-aarch64-rockchip-**bsp6.1**-joshua-git

so that i will make it

linux-aarch64-rockchip-**bsp5.10**-radxa-git

since radxa kernels work rock4/rock5 variants including rk3399, rk356x, rk358x in single config ("rock-4se" "rock-pi-4a-plus" "rock-pi-4b-plus" "rock-4c-plus" "rock-pi-4a" "rock-pi-4b" "rock-pi-4c" "rock-4-core-io" "radxa-nx5-io" "rock-5-itx" "rock-5a" "rock-5b" "rock-5b-plus" "radxa-cm5-io" "radxa-cm5-rpi-cm4-io") i will not define a specific soc variant,

**Comment by hbiyik** [comment]
or an alternative approach, mentioning the version in package name is not nice and generates long names.

it could also be:

pkgname= linux-aarch64-rockchip-radxa-git
pkgver = bsp.5.10.1293801

so use actually pkgver to designate the version, syntax may differ

**Comment by 7Ji** [comment]
Yeah -bsp[ver] would be cleaner, and 

> so that i will make it
>
> linux-aarch64-rockchip-**bsp5.10**-radxa-git

That would be reasonable.



> or an alternative approach, mentioning the version in package name is not nice and generates long names.
> 
> it could also be:
> 
> pkgname= linux-aarch64-rockchip-radxa-git pkgver = bsp.5.10.1293801
> 
> so use actually pkgver to designate the version

No, that would make bsp5.10 and bsp6.1 unable to co-exist. This invalidates a point on using the BSP kernel: use what's stable, but not what's latest.

**Comment by hbiyik** [comment]
ah yeah true, obviously :)

**Comment by hbiyik** [comment]
ok  there is one particular problem.

linux-aarch64-rockchip-rk3588-bsp5.10-orangepi-git

this is too long, i can not write it twice without looking at it.

**Comment by 7Ji** [comment]
Well name length is a sacrifice we need to make if we need to navigate through all these different bsp kernel packages, and host them in a single namespace where x86_64 and aarch64 PKGBUILDs co-exist, and riscv and other arches are coming. 

They could be shorter if we stay mainline, aarch64 only, or bsp but only one particular version. But we have to fight the fact that every board maker has their own idea on the kernel and there's no one single centralised kernel effort other than the not-for-production-yet mainline.

**Comment by hbiyik** [comment]
Renamed:
[linux-aarch64-rockchip-bsp5.10-radxa](https://github.com/7Ji-PKGBUILDs/linux-aarch64-rockchip-bsp5.10-radxa) : from `linux-radxa-rkbsp5-git`

Archived:
`linux-radxa-rkbsp5-bin`

**Comment by kyak** [comment]
Is it really necessary to have *this* many kernel packages?

With exciting development going on in panthor, why not just dump those 5.10 kernels?

Or at least tell it very clear which kernel users should stick to.

Currently, as I understand, even @hbiyik and @7Ji are using different kernels. Why do we spread efforts?

**Comment by hbiyik** [comment]
i hope @joshua-riek's effort to combine several board support at one kernel will help. But until then it is very reasonable to use the board specific kernel maintained by the board manufacturer, not to deal with funky kernel issues.

I think there will be a day that rockchip 5.10 kernel will be dumped as well, but i think there is still time for that.

Panthor is a different story still, i will backport this from mainline to 6.1 rockchip kernel. Even though it works on mainline, mainline kernel support for rockchip is not the best, frequency driver, pvtm, power saving, hdmi, displaye driver (vop2) is some of the few i can tell from the top of my head which is missing or implemented with missing subset of features in mainline. So i think i wont daily mainline even with panthor...

**Comment by wyf9661** [comment]
> Is it really necessary to have _this_ many kernel packages?

yes, even on x86, there are so many kernels (lts, hardend, zen ,xanmod and so on) for users to select the one fits, we just provide kernel package, we do not judge.
> Why do we spread efforts?

Maybe this is the 'kernel' of opensource, we learn from each other, we find out what we need and make things better.

**Comment by kwankiu** [comment]
@wyf9661 

since we have Joshua’s 6.1.43 working well

I see that you have another branch based on rockchip’s (JeffyCN) branch
https://github.com/7Ji-PKGBUILDs/linux-aarch64-rockchip-bsp6.1

Would you consider bumping to 6.1.57?
https://github.com/JeffyCN/mirrors/tree/kernel-6.1-2024_03_01

**Comment by wyf9661** [comment]
> I see that you have another branch based on rockchip’s (JeffyCN) branch https://github.com/7Ji-PKGBUILDs/linux-aarch64-rockchip-bsp6.1
> 
> Would you consider bumping to 6.1.57? https://github.com/JeffyCN/mirrors/tree/kernel-6.1-2024_03_01

oh, I create this repo to separate patches with rkbsp, so that I can bump kernel easily, I missed some drivrers and this package does not work well, I will to have a try after I set up package based on 6.1.43, thanks for your advice.

**Comment by hbiyik** [comment]
@7Ji 
i needed to rename the git repo for radxa kernel once again

linux-aarch64-rockchip-bsp5.10-radxa -> linux-aarch64-rockchip-bsp5.10-radxa-git

forgot the `-git` suffix, PKGBUILD was fine and no changes.

**Comment by wyf9661** [comment]
> Would you consider bumping to 6.1.57? https://github.com/JeffyCN/mirrors/tree/kernel-6.1-2024_03_01

Finished.
![image](https://github.com/7Ji-PKGBUILDs/.meta/assets/122584107/da7bca7a-3c6e-4ab3-8c74-5c831022a37a)
