### ISSUE TITLE
Rockchip mpp related packages renaming/refactoring

### ISSUE THREAD

**Issue by hbiyik** [7Ji-PKGBUILDs/.meta#25]
So there is no more https://github.com/hbiyik/FFmpeg

therefore i am preparing for the weekend work. It will be faster if i have a clean agenda.

my suggestion:
rename : ffmpeg-rockchip-git -> ffmpeg-mpp-git (provides: ffmpeg-mpp)
archive: ffmpeg-mpp
archive : ffmpeg4.4-mpp, no more supported, only vlc uses it. dont use vlc, use mpv
archive : mpp (there already is mpp-git, and the broken commit was reverted, maintaining a seperate package mpp is not 
helping to save limited maintanence resources)
rename:  kodi-nexus-mpp-git -> kodi-mpp-git
archive: kodi-nexus-addon-inputstream-adaptive-git
archive: kodi-matrix-mpp-git
archive: kodi-matrix-addon-pvr-iptvsimple-git
archive: kodi-matrix-addon-inputstream-adaptive-git

objections? suggestions?

**Comment by 7Ji** [comment]
Looks good to me

**Comment by kyak** [comment]
@hbiyik couple of questions.

* Will `kodi-mpp-git` still track the `nexus` branch of Kodi after renaming? Does it make sense to track master branch of kodi or provide a package like `kodi-latest-mpp-git` that tracks the master branch?
* Will `kodi-mpp-git` use system ffmpeg, i.e. `ffmpeg-mpp-git`?
* What will happen to packages `kodi-addon-inputstream-adaptive` and `kodi-addon-pvr-iptvsimple`? What will be the way to install them?

**Comment by 7Ji** [comment]
@kyak 
I think `kodi-mpp-git` could track whatever branch hbiyik sees fit, for now it's `nexus`, but one day it would switch to `omega`, and so on and so on.

`latest` doesn't really make sense here. Versioned package names are for old stuffs, not for latest stuffs. Like there's no `ffmpeg-latest` vs `ffmpeg4.4` but `ffmpeg` vs `ffmpeg4.4`, `latest` is implicit and doesn't need to be there in the name.

**Comment by hbiyik** [comment]
> @hbiyik couple of questions.
> 
>     * Will `kodi-mpp-git` still track the `nexus` branch of Kodi after renaming? Does it make sense to track master branch of kodi or provide a package like `kodi-latest-mpp-git` that tracks the master branch?

it will always follow the git branch of the [current latest released version](https://kodi.wiki/view/Releases) of kodi (the green part in the table of the link). Running the master branch of kodi is very risky for a daily user, therefore i dont think such kodi-latest-mpp-git package is necessary.

>     * Will `kodi-mpp-git` use system ffmpeg, i.e. `ffmpeg-mpp-git`?

Currently nexus branch uses ffmpeg4.x, i have forward ported it to ffmpeg5.x, and rebased ffmpeg-rockchip to 5.1.2 [here](https://github.com/hbiyik/ffmpeg-rockchip/tree/5.1.2), so nexus branch can not work with system ffmpeg which is 6.x based. Therefore i am compiling ffmpeg-rockchip 5.x once again inside kodi ans static linking kodi to it, it does not use the exact system ffmpeg.

Omega has ffmpeg 6.x support but there are some issues related to that afaik so when the kodi package switches to omega, i might switch to use system ffmpeg may be, not yet decided that, it also depends how team kodi will maintain ffmpeg compatability in future releases, i see bigger care in there from team kodi when compared to past.

>     * What will happen to packages `kodi-addon-inputstream-adaptive` and `kodi-addon-pvr-iptvsimple`? What will be the way to install them?

For that you can use [agr](https://github.com/hbiyik/agr), to install kodi-binary-addons-git package in the [agr repo](https://github.com/hbiyik/agrrepo) here. This package not only contains is-adaptive or iptvsimple, but all binary addons (80+) in total, including emulator and game support vfs etc, everything. But it is a huge package so no need to torture and put it in here, instead interested people can compile on their own machine with agr.

**Comment by hbiyik** [comment]
@kwankiu since this change will most likely make your life little bit harder, any comments?

**Comment by kwankiu** [comment]
> So there is no more https://github.com/hbiyik/FFmpeg
> 
> therefore i am preparing for the weekend work. It will be faster if i have a clean agenda.
> 
> my suggestion: rename : ffmpeg-rockchip-git -> ffmpeg-mpp-git (provides: ffmpeg-mpp) archive: ffmpeg-mpp archive : ffmpeg4.4-mpp, no more supported, only vlc uses it. dont use vlc, use mpv archive : mpp (there already is mpp-git, and the broken commit was reverted, maintaining a seperate package mpp is not helping to save limited maintanence resources) rename: kodi-nexus-mpp-git -> kodi-mpp-git archive: kodi-nexus-addon-inputstream-adaptive-git archive: kodi-matrix-mpp-git archive: kodi-matrix-addon-pvr-iptvsimple-git archive: kodi-matrix-addon-inputstream-adaptive-git
> 
> objections? suggestions?

So basically after the renaming we will only have this three packages, correct?
- ffmpeg-mpp-git
- mpp-git
- kodi-mpp-git

and what would be the solution if someone still prefer using VLC?

**Comment by hbiyik** [comment]
current vlc even with ffmpeg-mpp sucks anyways, it can at make 2k, at max. This can also be achieved with soft decoding with cpu decoding.

edit: to answer original question, yes, less is more.. only 3 in this repo + kodi-binary-addons-git in agr

**Comment by hbiyik** [comment]
@7Ji 
ffmpeg*
kodi-*
mpp
linux-radxa-*
in above repos, i do not seem to have the permission to make archive or to access repo settings, could you grant that?

**Comment by 7Ji** [comment]
> @7Ji ffmpeg* kodi-* mpp linux-radxa-* in above repos, i do not seem to have the permission to make archive or to access repo settings, could you grant that?

I've promoted the base permissions from `write` to `admin`, can you archive and rename them now?

**Comment by hbiyik** [comment]
thanks it works now

**Comment by erayrafet** [comment]
Any way we can test the updated packages?

**Comment by hbiyik** [comment]
just pushed the changes,

you can use agr to instantly test:
https://github.com/hbiyik/agr

to test from 7ji repo they need to be rebuilt.

**Comment by hbiyik** [comment]
Renamed:
[ffmpeg-mpp-git](https://github.com/7Ji-PKGBUILDs/ffmpeg-mpp-git) from `fmpeg-rockchip-git`
[kodi-mpp-git](https://github.com/7Ji-PKGBUILDs/kodi-mpp-git) from `kodi-nexus-mpp-git`

archived
`ffmpeg-mpp`
`ffmpeg4.4-mpp`
`mpp`
`kodi-nexus-addon-inputstream-adaptive-git`
`kodi-matrix-mpp-git`
`kodi-matrix-addon-pvr-iptvsimple-git`
`kodi-matrix-addon-inputstream-adaptive-git`

**Comment by erayrafet** [comment]
![image](https://github.com/7Ji-PKGBUILDs/.meta/assets/34194191/fb05f7a0-793e-42ad-b0e9-5768c4301a82)
agr is always trying to install mesa-panfork-joshua-6-git when I want it to install mpp and kodi.
Possibly an agr issue but seems related.

**Comment by kwankiu** [comment]
> ![image](https://private-user-images.githubusercontent.com/34194191/311124386-fb05f7a0-793e-42ad-b0e9-5768c4301a82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTQ1NjQsIm5iZiI6MTcwOTg5NDI2NCwicGF0aCI6Ii8zNDE5NDE5MS8zMTExMjQzODYtZmIwNWY3YTAtNzkzZS00MmFkLWIwZTktNTc2OGM0MzAxYTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDEwMzc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZmI2ODdjZWQ3YTI4MDg2NWJmYjBmNWM0MDAwOGIyNTE3N2ZiM2VmOWU4ZTY4MzBkNTA2OWViMmRhYThmYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jn2use3YulMMha0_IZKWNVGGgty5BZQgLx3rE63KOQE) agr is always trying to install mesa-panfork-joshua-6-git when I want it to install mpp and kodi. Possibly an agr issue but seems related.

What is the command you run with agr?
Maybe try remove my repo when you install boogie's kodi

**Comment by erayrafet** [comment]
> > ![image](https://private-user-images.githubusercontent.com/34194191/311124386-fb05f7a0-793e-42ad-b0e9-5768c4301a82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4OTQ1NjQsIm5iZiI6MTcwOTg5NDI2NCwicGF0aCI6Ii8zNDE5NDE5MS8zMTExMjQzODYtZmIwNWY3YTAtNzkzZS00MmFkLWIwZTktNTc2OGM0MzAxYTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDEwMzc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZmI2ODdjZWQ3YTI4MDg2NWJmYjBmNWM0MDAwOGIyNTE3N2ZiM2VmOWU4ZTY4MzBkNTA2OWViMmRhYThmYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jn2use3YulMMha0_IZKWNVGGgty5BZQgLx3rE63KOQE) agr is always trying to install mesa-panfork-joshua-6-git when I want it to install mpp and kodi. Possibly an agr issue but seems related.
> 
> What is the command you run with agr? Maybe try remove my repo when you install boogie's kodi

I removed your repo and we got rid of the panfork error  Currently debugging building ffmpeg.

**Comment by kwankiu** [comment]
@hbiyik I noticed that your agrepo takes more than 30 seconds to fetch and agr seems tries to compile and replace the system's mesa installed with pacman from 7Ji with the one from your repo when you just run ```agr update```.

**Comment by hbiyik** [comment]
@kwankiu @erayrafet lets move those discussions to hbiyik/agr repo.
