### ISSUE TITLE
clang versions seems to be broken in ALARM

### ISSUE THREAD

**Issue by hbiyik** [7Ji-PKGBUILDs/.meta#26]
https://archlinuxarm.org/packages/aarch64/clang is on version 17
but the actual repo is at 16 on clang, and 17 at llvmlibs.

```
[alarm@alarm ~]$ pacman -Q | grep clang
clang 16.0.6-2
[alarm@alarm ~]$ pacman -Q | grep llvm-libs
llvm-libs 17.0.6-2
```

may be it is not built on ALARM or may be CDN messed up, i am on `http://de3.mirror.archlinuxarm.org/$arch/$repo` mirror.

this causes v4l-utils-mpp not to compile.

**Comment by 7Ji** [comment]
The site is generated from PKGBUILDs metadata, not actual package file. If you click the "Download" button the link would lead you to a 404 link. So, clang17 is not available in their official mirrors, and probably not built yet (or built but not pushed, as all stuffs dependent on clang would need to be rebuilt and synced together)

**Comment by hbiyik** [comment]
yeah i assumed the same as well, but you cant have llvm libs on 17 but clang on 16, they need to react to that.

our impacted packages are worked around in below commits
https://github.com/7Ji-PKGBUILDs/v4l-utils-mpp/commit/40c649b7f21f37bf4a1498782203365fdc479e3f
https://github.com/7Ji-PKGBUILDs/ffmpeg-mpp-git/commit/fcc2357634e6fcb3fac0555e59ce0695d9fdd899

**Comment by hbiyik** [comment]
ah great kodi is also impacted... i might tilt..

worked around in this commit as well
https://github.com/7Ji-PKGBUILDs/kodi-mpp-git/commit/9e22f21f514286f0f77d9cba0b11e9eaf7011dae

to verify run `clang` if you receive an error like below.

```shell
[alarm@alarm kodi-mpp-git]$ clang
clang: error while loading shared libraries: libLLVM-16.so: cannot open shared object file: No such file or directory
```

just remove clang with

`sudo pacman -Rcns clang`

because kodi build system will try to use `clang-format` as long as it is available in the system, so in this interim stage you can remove `clang` it does not work anyway.

Sidenote: seems like `chromium-mpp` package is also using clang and it will most likely fail to build until alarm fixes clang versions.

Sidenote2: even rust compiler is broken... this is really bad.

**Comment by 7Ji** [comment]
At this stage I think we shouldn't jump the gun. I'd prefer we just stick to what these PKGBUILDs are and wait, instead of fixing all of them up and reverting all changes after ALARM fix

**Comment by 7Ji** [comment]
So the current situation is that:
 - ALARM does not have their own downstream `llvm` (providing `llvm-libs`) and `clang` PKGBUILD. [ref their local PKGBUILDs for extra repo](https://github.com/archlinuxarm/PKGBUILDs/tree/master/extra)
 - [Arch PKGBUILD for llvm](https://gitlab.archlinux.org/archlinux/packaging/packages/llvm/-/blob/main/PKGBUILD?ref_type=heads) was updated to 17, 6 days ago. This change landed in ALARM in the past 1 or 2 days.
 - [Arch PKGBUILD for clang](https://gitlab.archlinux.org/archlinux/packaging/packages/clang/-/blob/main/PKGBUILD?ref_type=heads) was updated to 17, also 6 days ago, same time as `llvm`. This change has not landed in ALARM yet.

I think changes that are meant to "work around" the current situations should be halted for this week. Let's wait to see if ALARM solves the clang problem by themselves.

**Comment by hbiyik** [comment]
clang is back to normal i will revert the workarounds
