### ISSUE TITLE
Kernel packages should not provide `/etc/mkinitcpio.d/${pkgname}.preset` any more

### ISSUE THREAD

**Issue by 7Ji** [7Ji-PKGBUILDs/.meta#28]
After the recent update of `mkinitcpio`, all preset files under `/etc/mkinitcpio.d` shall be generated by `mkinitcpio` itself, not provided by kernel packages:
```
> LANG=C pacman -Qo /etc/mkinitcpio.d/linux-zen.preset
error: No package owns /etc/mkinitcpio.d/linux-zen.preset
```

A related discussion thread on `arch-general` list: https://lists.archlinux.org/hyperkitty/list/arch-general@lists.archlinux.org/thread/CNCMK2Y3BUWR5B5C54V6TPHEJKBS7HGT/

@hbiyik @wyf9661 Let's follow the Arch change.

**Comment by hbiyik** [comment]
ok i ll do that, we are sure alarm has those hooks right? seems like a very recent change.

**Comment by hbiyik** [comment]
done: https://github.com/7Ji-PKGBUILDs/linux-aarch64-rockchip-bsp5.10-radxa-git/commit/3b7db2f5233f827c5696e6df96b75260df8b1a3f
