### ISSUE TITLE
`linux-panthor` & `mesa-panthor`: WIP mainline panthor packages

### ISSUE THREAD

**Issue by 7Ji** [7Ji-PKGBUILDs/.meta#3]
quote @hbiyik :
> i am experimenting with mainline linux with panthor and mesa, pushed two packages

> those panthor things are very buggy atm no need to build them.

Manually transferred from an internal private list

**Comment by wyf9661** [comment]
@nyanmisaka 
hello, 
I heard you have already use the panthor dirver form  [https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/x-org-drm/1426252-panthor-drm-driver-coming-together-for-newer-arm-mali-gpus](https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/x-org-drm/1426252-panthor-drm-driver-coming-together-for-newer-arm-mali-gpus) .
I try to build kernel with [https://githubfast.com/hbiyik/linux/commits/linux-6.1-gen-rkr6%2Bpanthor ](https://githubfast.com/hbiyik/linux/commits/linux-6.1-gen-rkr6%2Bpanthor) , after I restart the opi5-plus, I can enter the DE, which is really so nice that I can have a new experience.
But if I use panthor mesa driver [https://gitlab.freedesktop.org/bbrezillon/mesa.git](https://gitlab.freedesktop.org/bbrezillon/mesa.git) , select branch `v10+reg-cache`, the mesa vendor is still recognized as `llvmpipe`, is there any thing still need to be set？

Best wishes!

**Comment by wyf9661** [comment]
glmark in 3 confitions below:
![img_v3_026j_62f6babc-1abc-46d0-8e07-e6265274929g](https://github.com/7Ji-PKGBUILDs/.report/assets/122584107/4a4c3360-8b7d-4ec6-b388-e624b55d4755)
![img_v3_026j_0873be92-11cc-405e-b9d5-9a699273632g](https://github.com/7Ji-PKGBUILDs/.report/assets/122584107/52b5daf4-82a1-4903-8f97-0d18fefc56ea)

panthor:
`Error: Failed to find suitable GLX FB config 
Error: Error: Couldn't get GL visual config! 
Error: main: Could not initialize canvas`

**Comment by wyf9661** [comment]
I will have a try
![图片](https://github.com/7Ji-PKGBUILDs/.report/assets/122584107/5a969958-8daa-42b4-8ef2-a7a11cf9054b)

**Comment by wyf9661** [comment]
change branch to `panthor`
```
[    2.654066] panthor fb000000.gpu: [drm:panthor_devfreq_init [panthor]] Failed to register cooling device
[    2.661127] panthor fb000000.gpu: [drm] mali-g610 id 0xa867 major 0x0 minor 0x0 status 0x5
[    2.661868] panthor fb000000.gpu: [drm] Features: L2:0x7120306 Tiler:0x809 Mem:0x301 MMU:0x2830 AS:0xff
[    2.662688] panthor fb000000.gpu: [drm] shader_present=0x50005 l2_present=0x1 tiler_present=0x1
[    2.664051] panthor fb000000.gpu: Direct firmware load for mali_csffw.bin failed with error -2
[    2.664811] panthor fb000000.gpu: [drm] *ERROR* Failed to load firmware image 'mali_csffw.bin'
[    2.665733] panthor: probe of fb000000.gpu failed with error -2
```

**Comment by wyf9661** [comment]
![图片](https://github.com/7Ji-PKGBUILDs/.report/assets/122584107/a440f8ec-a0f9-4920-8e4b-d63ca592f216)

**Comment by hbiyik** [comment]
@wyf9661 sorry i have not seen this issue before. Those packages are experimental, i have stopped working on panthor since it is still changing so freqeuntly. I would just wait until it is published officially.

**Comment by 7Ji** [comment]
I guess we can close this issue as not planned and archive those two PKGBUILDs?
