### ISSUE TITLE
Widevine for chromium-mpp?

### ISSUE THREAD

**Issue by erayrafet** [7Ji-PKGBUILDs/.meta#32]
So far that's something missing. It would improve the experience immensely for us Arch users.

Here are some resources:
https://forums.raspberrypi.com/viewtopic.php?t=347736
https://github.com/AsahiLinux/widevine-installer

**Comment by 7Ji** [comment]
> NOTE: Using Widevine requires glibc version 2.36 or later. Arch Linux ARM ships an ancient glibc version, and will not work at this time. 

ALARM ships glibc 2.35 while Arch ships 2.39, it's not possible to run Widewine on official ALARM.
