### ISSUE TITLE
kodi-mpp-git is missing from repo

### ISSUE THREAD

**Issue by kyak** [7Ji-PKGBUILDs/.meta#33]
kodi-mpp-git has disappeared from the repo's packages.

Do you know why?

**Comment by 7Ji** [comment]
It's failing to build right now with latest deps and sources:

```
[100%] Building CXX object build/swig/CMakeFiles/python_binding.dir/AddonModuleXbmc.i.cpp.o
/srv/repo/build/kodi-mpp-git/src/kodi-build/build/swig/AddonModuleXbmcaddon.i.cpp: In function 'PyObject* PythonBindings::xbmcaddon_XBMCAddon_xbmcaddon_Settings_New(PyTypeObject*, PyObject*, PyObject*)':
/srv/repo/build/kodi-mpp-git/src/kodi-build/build/swig/AddonModuleXbmcaddon.i.cpp:1610:52: error: no matching function for call to 'XBMCAddon::xbmcaddon::Settings::Settings()'
 1610 |     apiResult = new XBMCAddon::xbmcaddon::Settings();
      |                                                    ^
In file included from /srv/repo/build/kodi-mpp-git/src/xbmc/xbmc/interfaces/legacy/Addon.h:14,
                 from /srv/repo/build/kodi-mpp-git/src/kodi-build/build/swig/AddonModuleXbmcaddon.i.cpp:28:
/srv/repo/build/kodi-mpp-git/src/xbmc/xbmc/interfaces/legacy/Settings.h:60:3: note: candidate: 'XBMCAddon::xbmcaddon::Settings::Settings(std::shared_ptr<CSettingsBase>)'
   60 |   Settings(std::shared_ptr<CSettingsBase> settings);
      |   ^~~~~~~~
/srv/repo/build/kodi-mpp-git/src/xbmc/xbmc/interfaces/legacy/Settings.h:60:3: note:   candidate expects 1 argument, 0 provided
make[2]: *** [build/swig/CMakeFiles/python_binding.dir/build.make:125: build/swig/CMakeFiles/python_binding.dir/AddonModuleXbmcaddon.i.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:13173: build/swig/CMakeFiles/python_binding.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
==> ERROR: A failure occurred in build().
```

Also I've lost the last successful build after I issued a full repo update thinking every pkg was successfully built, sorry.

**Comment by kyak** [comment]
kodi v21.0-Omega was released yesterday: https://github.com/xbmc/xbmc/releases/tag/21.0-Omega

Perhaps we should switch to it.

**Comment by hbiyik** [comment]
@kyak @7Ji i will just migrate to Omega ill ping when done

**Comment by hbiyik** [comment]
done, 
kodi-mpp-git is upgraded to Omega

kodi-binary-addons-git
kodi-nexus-mpp-git
kodi-nexus-binary-addons-git

is on [agr](https://github.com/hbiyik/agrrepo)

**Comment by kyak** [comment]
> done, kodi-mpp-git is upgraded to Omega
> 
> kodi-binary-addons-git kodi-nexus-mpp-git kodi-nexus-binary-addons-git
> 
> is on [agr](https://github.com/hbiyik/agrrepo)

Thanks!

I'm trying to build from your PKGBUILD locally.

`rapidjson` and `tinyxml2` are missing from makedepends. I get according errors from cmake.

**Comment by hbiyik** [comment]
thanks for reporting is it building with those?

**Comment by kyak** [comment]
> thanks for reporting is it building with those?

yeah

**Comment by hbiyik** [comment]
closing then, i added the missing deps, in case of issues feel free to repopen
