### ISSUE TITLE
arch arm port

### ISSUE THREAD

**Issue by hbiyik** [7Ji-PKGBUILDs/.meta#35]
@7Ji 
have you seen this, this looks very nice...

https://gitlab.archlinux.org/archlinux/rfcs/-/merge_requests/32

**Comment by 7Ji** [comment]
Thank you for reminding. I've read about arch port a couple of weeks ago, when Felix (Arch dev & Arch PM & Arch RISC-V creator) was discussing that in #archlinuxcn group before the RFC was created.

For sure, the situation of ALARM will improve a lot when Arch adopts ports. But as Arch basically follows mainline, vendor-specific stuffs, especially kernel & decoding packages that we are maintaining, would unlikely get into official repos. They'll stay non-official, port or not, AUR or under another git hoster.

I'll keep this org and my repo up and running, as always.

**Comment by 7Ji** [comment]
FYI the Arch port RFC was merged 5 days ago, and it's now available on the Arch RFC pages:
https://rfc.archlinux.page/0032-arch-linux-ports/
