### ISSUE TITLE
GCC 14 and toolchain update

### ISSUE THREAD

**Issue by hbiyik** [7Ji-PKGBUILDs/.meta#36]
just happened yesterday or so for alarm, expect some things to break soon.

Just a communication thread.

**Comment by JFLim1** [comment]
Updated successfully -Archlinux-Gnome-6.1.43-joshua-panthor-git.  Chromium-mpp, mpv, LibreOffice seem to work ok.

Edit: Also tested Archlinux-Gnome-inux-aarch64-rockchip-rk3588-bsp5.10-orangepi-git with mesa-panfork-git seem to work as per normal so far.

Thanks.

**Comment by hbiyik** [comment]
v4lutils-mpp, libv4l-rkmpp, gl4es-git, kodi-mpp-git, dri2to3-git,mesa-panfork-git, librga-multi, mpp-git,ffmpeg-mpp-git
also works after several patches, now i tested both on `aarch64` and `armv7h`

radxa-kernel works for 'aarch64', so everthing seems to be fine.

known issues that the change impacts:.

_gcc14:_ c++ `std:find` method is no more included by default with gcc 14, one needs to manually include `<algorithm.h>`
_python13_: removed the support of `distutils`, if the package or the build system of it depends on `distutils` you might face issues

**Comment by hbiyik** [comment]
seems like everything is sattled, closing
