### ISSUE TITLE
`linux-aarch64-rockchip-bsp5.10-radxa-git` fails to build

### ISSUE THREAD

**Issue by 7Ji** [7Ji-PKGBUILDs/.meta#38]
It's broken recently
```
drivers/net/bonding/bond_alb.c:1375:13: error: conflicting types for 'bond_tlb_xmit' due to enum/integer mismatch; have 'netdev_tx_t(struct sk_buff *, struct net_device *)' {aka 'enum netdev_tx(struct sk_buff *, struct net_device *)'} [-Werror=enum-int-mismatch]
 1375 | netdev_tx_t bond_tlb_xmit(struct sk_buff *skb, struct net_device *bond_dev)
      |             ^~~~~~~~~~~~~
In file included from ./include/net/bonding.h:30,
                 from drivers/net/bonding/bond_alb.c:24:
./include/net/bond_alb.h:160:5: note: previous declaration of 'bond_tlb_xmit' with type 'int(struct sk_buff *, struct net_device *)'
  160 | int bond_tlb_xmit(struct sk_buff *skb, struct net_device *bond_dev);
      |     ^~~~~~~~~~~~~
```

@hbiyik FYI

**Comment by hbiyik** [comment]
thx ill check it, i remember this from somewhere else.

**Comment by kwankiu** [comment]
Is this going to get fixed anytime soon?

@7Ji , @hbiyik FYI, i have the following pkgbuilds built from latest radxa's deb kernel package release:

Radxa BSP5.10
https://github.com/kwankiu/PKGBUILDs/tree/rockchip/linux-aarch64-rockchip-bsp5.10-radxa

Radxa BSP6.1
https://github.com/kwankiu/PKGBUILDs/tree/rockchip/linux-aarch64-rockchip-bsp6.1-radxa

**Comment by kwankiu** [comment]
@wyf9661 @7Ji, I have submitted a PR on https://github.com/7Ji-PKGBUILDs/linux-aarch64-rockchip-armbian-git

**Comment by hbiyik** [comment]
@kwankiu  @7Ji fixed in https://github.com/7Ji-PKGBUILDs/linux-aarch64-rockchip-bsp5.10-radxa-git/commit/aab7eee53efe56e9600f71151560a65fbd2ce6d0

**Comment by hbiyik** [comment]
@7ji ffmpeg is also now updated to 7.0

**Comment by 7Ji** [comment]
Thanks! Closing now.
