### ISSUE TITLE
update 5.10 kernel to support new Radxa boards

### ISSUE THREAD

**Issue by kwankiu** [7Ji-PKGBUILDs/.meta#39]
`linux-aarch64-rockchip-bsp5.10-joshua` is not updated since 3 months ago while `linux-aarch64-rockchip-bsp5.10-radxa-git` is unavailable right now. 

The kernel needs to be updated in order to support the following new radxa boards like:
- radxa-cm5-rpi-cm4-io
- radxa-rock-5c
- radxa-rock-5-itx

- radxa-rock-5d
- radxa-rock-5b-plus

**Comment by 7Ji** [comment]
This is wyf9661 's PKGBUILD and I'm not currently using / debugging it. Ping @wyf9661  for notification.

That being said, if you want to update the package, you can do it yourself. Open a PR to the said PKGBUILD. After that PR being merged I can invite you to join the org to modify it however as you like.

**Comment by wyf9661** [comment]
I suggest changing the base kernel to v6.1 as the upstream of v5.10 updates so slowly in recent days, another reason for me not updating this PKGBUILDS is that the kernel tag became so messy after '[5.10.160-37](https://github.com/Joshua-Riek/linux-rockchip/releases/tag/5.10.160-37)', if you still need to use `5.10`, I will probably change this repo to a `git version`

**Comment by kwankiu** [comment]
> I suggest changing the base kernel to v6.1 as the upstream of v5.10 updates so slowly in recent days, another reason for me not updating this PKGBUILDS is that the kernel tag became so messy after '[5.10.160-37](https://github.com/Joshua-Riek/linux-rockchip/releases/tag/5.10.160-37)', if you still need to use `5.10`, I will probably change this repo to a `git version`

Changing this to git would be great to ensure compatitbility with newer boards, but i wouldnt say it is a great idea to go for v6.1 and drop 5.10 yet for reliablitiy and compatitbility, at least, both radxa and khadas are still on 5.10, radxa are testing v6.1 but they are only available on their github as development build. Moreover, from what i've heard of, many games and emulators doesnt work on this v6.1 kernel.

**Comment by 7Ji** [comment]
It's 5.10-git, all BSP kernels here track a specific major.minor version
