### ISSUE TITLE
`mesa-panfork-git`: Regression when used with newer `xbmc`

### ISSUE THREAD

**Issue by 7Ji** [7Ji-PKGBUILDs/.meta#4]
quote @hbiyik :
> and now due to this https://github.com/xbmc/xbmc/issues/24122#issuecomment-1819870709 issue, panfork needs another update.

Manually transferred from a private list

**Comment by 7Ji** [comment]
FYI the updated package containing the fix https://github.com/7Ji-PKGBUILDs/mesa-panfork-git/commit/bc05b90fbd3c77526aca1db0f02e2998cf5048dc is already uploaded:
https://github.com/7Ji/archrepo/releases/download/aarch64/mesa-panfork-git-r164484.120202c6757-2-aarch64.pkg.tar.zst

**Comment by 7Ji** [comment]
I assume this is fixed? Should we close the issue? @hbiyik

**Comment by hbiyik** [comment]
yep it is closed
