### ISSUE TITLE
`linux-aarch64-rockchip-armbian-git` is failing to build

### ISSUE THREAD

**Issue by 7Ji** [7Ji-PKGBUILDs/.meta#45]
Some upstream updates have resulted in broken DTB breaking the build

```
> grep -v '^  ' 20240725_024145_build_linux-aarch64-rockchip-armbian-git-f506024437ff233a8487bd64bfcc030e69ca3635-210acd080ed6f6ea-6.10.0.r22.232b42.d2535a.log  | grep -i error
Error: arch/arm64/boot/dts/rockchip/rk3588-armsom-sige7.dts:168.1-7 Label or path hdmi0 not found
Error: arch/arm64/boot/dts/rockchip/rk3588-armsom-sige7.dts:172.1-10 Label or path hdmi0_in not found
FATAL ERROR: Syntax error parsing input tree
make[3]: *** [scripts/Makefile.lib:445: arch/arm64/boot/dts/rockchip/rk3588-armsom-sige7.dtb] Error 1
make[2]: *** [scripts/Makefile.build:485: arch/arm64/boot/dts/rockchip] Error 2
make[1]: *** [/srv/repo/build/linux-aarch64-rockchip-armbian-git/src/linux-stable/Makefile:1397: dtbs] Error 2
make: *** [Makefile:224: __sub-make] Error 2
==> ERROR: A failure occurred in build().
```
[20240725_024145_build_linux-aarch64-rockchip-armbian-git-f506024437ff233a8487bd64bfcc030e69ca3635-210acd080ed6f6ea-6.10.0.r22.232b42.d2535a.log.gz](https://github.com/user-attachments/files/16369642/20240725_024145_build_linux-aarch64-rockchip-armbian-git-f506024437ff233a8487bd64bfcc030e69ca3635-210acd080ed6f6ea-6.10.0.r22.232b42.d2535a.log.gz)

@kwankiu @wyf9661  FYI

**Comment by kwankiu** [comment]
Noted. Will check it out soon.

Btw, do you think it is a good idea to have armbian BSP kernel pkgbuild maintained here?

It is currently on my own repo:
https://github.com/kwankiu/PKGBUILDs/tree/rockchip/linux-aarch64-rockchip-bsp6.1-armbian-git

As well as its firmware:
https://github.com/kwankiu/PKGBUILDs/tree/rockchip/linux-firmware-armbian-git

**Comment by kwankiu** [comment]
@7Ji, mainline seems to be on 6.11-rc1 

the version we are building shows 6.10.0.r22.232b42.d2535a

not sure if that matters but i see the patches are failing, 

we would likely need to wait for armbian to release patch for 6.11 or we can switch to stable 6.10.1

**Comment by kwankiu** [comment]
Switched to linux-6.10.y

https://github.com/7Ji-PKGBUILDs/linux-aarch64-rockchip-armbian-git/commit/90920fc83a121e2efa45d480c26084d949480473
