### ISSUE TITLE
Info for Chromium-mpp Debug: echo 7 | sudo tee /sys/module/rk_vcodec/parameters/mpp_dev_debug and dmesg -w

### ISSUE THREAD

**Issue by JFLim1** [7Ji-PKGBUILDs/.meta#50]
@7Ji,

Missed your request for information earlier. 

> echo 7 | sudo tee /sys/module/rk_vcodec/parameters/mpp_dev_debug and dmesg -w

```
dmesg -w

[ 4708.999601] irq_status=00000107
[ 4709.016701] irq_status=00000107
[ 4709.033253] irq_status=00000107
[ 4709.050156] irq_status=00000107
[ 4709.066318] irq_status=00000107
[ 4709.082975] irq_status=00000107
[ 4709.099891] irq_status=00000107
[ 4709.118035] irq_status=00000107
[ 4709.149241] irq_status=00000107
[ 4709.153017] irq_status=00000107
[ 4709.166225] irq_status=00000107
[ 4709.182690] irq_status=00000107
[ 4709.199587] irq_status=00000107
[ 4709.216146] irq_status=00000107

```
Keep repeating the same.

Apologies for not noticing your request for info on " echo 7 | sudo tee /sys/module/rk_vcodec/parameters/mpp_dev_debug and dmesg -w"

**Comment by kwankiu** [comment]
@7Ji, btw i have noticed that both armbian and joshua's ubuntu has switched back to shipping Chromium MPP v114 by default, what would you suggest on reverting to v114 or having both v114 and v126 available here?

**Comment by JFLim1** [comment]
Armbian images with kernel-6.1.75-vendor-rk35xx uses/link to amazingfate's rockchip legacy multimedia ppa which have access to both chromium-browser-rkmpp_v114 and chromium-rkmpp_v126.

**Comment by kwankiu** [comment]
> Armbian images with kernel-6.1.75-vendor-rk35xx uses/link to amazingfate's rockchip legacy multimedia ppa which have access to both chromium-browser-rkmpp_v114 and chromium-rkmpp_v126.

yes, the default installed one is v114

**Comment by 7Ji** [comment]
@kwankiu 

> what would you suggest on reverting to v114 or having both v114 and v126 available here?

I won't revert `chromium`, as it always tracks latest rk patches that I can support. You (or any one interested) can create a PKGBUILD `chromium-114` for 114 if you want to, forking from the old 114 commit and fixing building issues.
