### ISSUE TITLE
404 error kodi-mpp-git-r175823

### ISSUE THREAD

**Issue by Danibos** [7Ji-PKGBUILDs/.meta#51]
Hi,

i'm receiving an error when i'm trying to update Kodi:

error: could not get file «kodi-mpp-git-r175823..patch.1.6859877547-1-aarch64.pkg.tar.zst» desde github.com: The requested URL returned error: 404
warning: some files could not be received
error: the operation could not be performed (some files could not be downloaded)
Errors occurred, so packages will not be updated

Ignoring this pkg i can perform the system update with no issue

It's happening with the previous kernel version and the latest one: 6.1.75-rockchip-g34daad066ed2-dirty

kwankiu's build

Please let me know if you need more infos

Thanks for checking

Dani

**Comment by 7Ji** [comment]
Not a PKGBUILD issue, report issues about the repo at https://github.com/7Ji/archrepo
