### ISSUE TITLE
FMAC error on bsp6.1-joshua-git

### ISSUE THREAD

**Issue by Callyth** [7Ji-PKGBUILDs/.meta#52]
This is a driver error on the Orange Pi 5 Pro using `linux-aarch64-rockchip-bsp6.1-joshua-git`.
The version is `6.1.75-rockchip`.
I was able to rebuild the brcmfmac module from the kernel source and obtain the debug log.The debug options are `0x0013D55E`.
[arch-debug.log](https://github.com/user-attachments/files/17082402/arch-debug.log)
Reference: https://community.infineon.com/t5/Knowledge-Base-Articles/FMAC-Debugging/ta-p/246042
I found the following error:
```
arch kernel: brcmfmac: CONSOLE: 000000.059 wl0: wlc_iovar_op: txbf BCME -23 (Unsupported)
arch kernel: brcmfmac: CONSOLE: 000000.060 wl0: unable to find iovar "rsdb_mode"
arch kernel: brcmfmac: CONSOLE: 000000.061 wl0: wlc_iovar_op: rsdb_mode BCME -23 (Unsupported)
```
Initially, I suspected that the cause of the error was in the firmware, but since this firmware is the same as the one from linux-rockchip, I believe it should function properly.
So that leaves the driver or environment settings as potential causes.
Do you know anything about this kind of error?
Thank you in advance.

**Comment by hbiyik** [comment]
The only additional patch we put on joshua's kernel is panthor path https://github.com/7Ji-PKGBUILDs/linux-aarch64-rockchip-bsp6.1-joshua-git/blob/ad788683cf485a7c8173b315c165eb862de86c5f/PKGBUILD#L21

can you try with commenting out https://github.com/7Ji-PKGBUILDs/linux-aarch64-rockchip-bsp6.1-joshua-git/blob/ad788683cf485a7c8173b315c165eb862de86c5f/PKGBUILD#L56  and rebuilding your kernel?

If your issue persists, then better to discuss this on Joshua's repo.

**Comment by 7Ji** [comment]
Only package building recipe issues would be tracked here. If a package builds and provides whatever upstream or the packager intended then there's no issue for the building recipe.
